[build]
command = "npm run build"
publish = "robnwings2/build-output/"
base = "robnwings2"

[[redirects]]
from = "/*"
to ="/home"
status = 200

from = "/*"
to ="/menu"
status = 200

from = "/*"
to ="/contact"
status = 200





